Fix partially initialized module error (#134019)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/134019

 https://github.com/pytorch/pytorch/pull/132990 introduced dependency on `torch.version`, which might not be imported yet, and can result in  `AttributeError: partially initialized module 'torch' has no attribute 'version' (most likely due to a circular import)` if user starts its code with `import torch.cuda`

Fix it by importing `torch.version` explicitly

Test Plan: CI

Reviewed By: seemethere

Differential Revision: D61549284